In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv('insurance_pre.csv')

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [15]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
dependent=dataset['charges']

In [17]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor

param_grid = {'criterion':['mse','mae','friedman_mse'],
'max_features': ['auto','sqrt','log2'],
'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(independent, dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\SRIRAM\Anaconda3\lib\site-packages\sklearn\tree\_classes.py:363: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use `criterion='squared_error'` which is equivalent.
  FutureWarning,

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [20]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_


print("The R_score value for best parameter {}".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'mse', 'max_features': 'auto', 'splitter': 'best'}

In [22]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007785,0.000401,0.002387,4.823947e-04,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.727009,0.654145,0.733064,0.733289,0.682903,0.706082,0.032065,1
1,0.005391,0.000802,0.001990,1.165962e-05,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.678332,0.675377,0.658419,0.748449,0.686414,0.689398,0.030902,4
2,0.004188,0.000401,0.001994,1.725861e-06,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.708262,0.654554,0.617259,0.661867,0.745311,0.677450,0.044597,9
3,0.004588,0.000801,0.002194,7.463626e-04,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.586838,0.543958,0.654237,0.718560,0.661590,0.633037,0.061071,16
4,0.004590,0.000486,0.002197,3.978093e-04,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.715514,0.576105,0.726206,0.559357,0.750847,0.665606,0.080905,12
5,0.003590,0.000798,0.001995,6.308268e-04,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.699244,0.480323,0.585469,0.697926,0.664169,0.625426,0.083496,18
6,0.020951,0.000892,0.001993,2.720062e-06,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.736157,0.619085,0.712936,0.706594,0.737052,0.702365,0.043383,2
7,0.017353,0.000488,0.001995,7.008046e-07,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.676022,0.583957,0.698303,0.693284,0.706536,0.671620,0.044954,11
8,0.012567,0.001018,0.001600,4.957551e-04,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.637148,0.621077,0.732149,0.707663,0.735319,0.686671,0.048230,6
9,0.011364,0.001497,0.001799,3.872284e-04,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.670844,0.636712,0.766367,0.672508,0.687280,0.686742,0.043125,5
10,0.013563,0.001017,0.001795,3.988984e-04,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.640437,0.663999,0.643230,0.559158,0.621971,0.625759,0.035869,17
11,0.010578,0.000480,0.001595,4.876118e-04,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.716812,0.634547,0.741672,0.630871,0.670127,0.678806,0.044110,8
12,0.004986,0.001092,0.001596,4.888701e-04,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.705841,0.651890,0.729521,0.702385,0.680004,0.693928,0.026235,3
13,0.003989,0.000631,0.001197,3.989459e-04,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.682751,0.621090,0.734301,0.708965,0.674162,0.684254,0.037971,7
14,0.003591,0.000798,0.001795,7.467100e-04,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.760906,0.677240,0.581565,0.643015,0.590424,0.650630,0.065302,14
15,0.003192,0.000399,0.001596,4.886361e-04,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.684952,0.523809,0.679183,0.677900,0.639011,0.640971,0.060809,15
16,0.003192,0.000399,0.001396,4.884804e-04,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.705985,0.621284,0.643465,0.699554,0.703931,0.674844,0.035440,10
17,0.003391,0.000797,0.001795,3.987790e-04,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.684645,0.588495,0.637243,0.647951,0.717114,0.655090,0.043646,13

In [23]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:28
BMI:25
Children:0
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1

In [24]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[16577.7795]

C:\Users\SRIRAM\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"

In [25]:
#saving the model
import pickle

In [26]:
filename="finalised_gridCv_DecisionTress_withoutTrain&TestSplit.sav"

In [28]:
pickle.dump(grid,open(filename,'wb'))

In [36]:
#DEPLOYMENT
loaded_model=pickle.load(open("finalised_gridCv_DecisionTress_withoutTrain&TestSplit.sav",'rb'))
result=loaded_model.predict([[35,30,0,0,1]])
result

C:\Users\SRIRAM\Anaconda3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  "X does not have valid feature names, but"

array([20234.85475])